version: 2

sources:
  - name: capstone_project

      database: latest-project-410306
          tables:
                - name: capstone_project_table
                     
                           
                           

    database: latest-project-410306
    tables:
      - name: capstone_project_table
     
      
models:
  - name: stg_capstone_project_table
    description: ""
    columns:
      - name: exchangeId
        data_type: string
        description: ""

      - name: rank
        data_type: int64
        description: ""

      - name: baseSymbol
        data_type: string
        description: ""

      - name: baseId
        data_type: string
        description: ""

      - name: quoteSymbol
        data_type: string
        description: ""

      - name: quoteId
        data_type: string
        description: ""

      - name: priceQuote
        data_type: float64
        description: ""

      - name: priceUsd
        data_type: float64
        description: ""

      - name: volumeUsd24Hr
        data_type: float64
        description: ""

      - name: percentExchangeVolume
        data_type: float64
        description: ""

      - name: tradesCount24Hr
        data_type: int64
        description: ""

      - name: updated	
        data_type: int64
        description: ""
